name: cbj_hub
description: Easy to use open source Hub to control your smart devices from one app.
version: 1.0.0
homepage: https://cybearjinni.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.0-nullsafety.2
  # Allow returning more than one type of object
  equatable: ^2.0.3
  # Annotations for freezed
  freezed_annotation: ^0.14.2
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.1.4
  grpc: ^3.0.0
  # Convenient code generator for get_it
  injectable: ^1.4.1
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^0.9.1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.5.3
  protobuf: ^2.0.0
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.4

dev_dependencies:
  build_runner:
  # A generator for injectable library
  # Code generator for unions/pattern-matching/copy.
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  # Library for mocks
  mockito: ^5.0.10
  pedantic: ^1.11.1
  test: ^1.17.8
